### ISSUE TITLE
Maven artifact

### ISSUE THREAD

**Issue by rendaw** [jfager/jdiscript#5]
Would you please publish a maven artifact?

**Comment by jfager** [comment]
Thanks for the request.  I'll hopefully be able to get this started this weekend.

**Comment by jfager** [comment]
Just wanted to update, I am actively working on this, but only get fits and spurts of time to do so and it might be a week or two.

**Comment by Rendaw** [comment]
Likewise, I'm not doing any Java dev atm, and no rush anyway :) .  I created these tickets since I will do more Java dev in the future and having jdiscript will be way nicer than the available debuggers, but I don't have anything I'm trying to debug immediately.

Thanks again for looking into these requests!

**Comment by jfager** [comment]
Took a while, I know, but this is done now!  https://repo1.maven.org/maven2/org/jdiscript/jdiscript/0.9.0/

**Comment by electrocnic** [comment]
This maven dependency can help if anybody has struggles with their tools.jar: https://github.com/olivergondza/maven-jdk-tools-wrapper
It worked for me.
